[colors.bright]
black = "0x1c61c2"
blue = "0x00ff00"
cyan = "0x0abdc6"
green = "0xd300c4"
magenta = "0x711c91"
red = "0xff0000"
white = "0xd7d7d5"
yellow = "0xf57800"

[colors.cursor]
cursor = "#FFD700"
text = "#2F343F"

[colors.normal]
black = "0x123e7c"
blue = "0x123e7c"
cyan = "0x0abdc6"
green = "0xd300c4"
magenta = "0x711c91"
red = "0xff0000"
white = "0xd7d7d5"
yellow = "0xf57800"

[colors.primary]
background = "#121220"
foreground = "#FF1C8D"

[font]
size = 10.0

[window]
opacity = 0.75
